language: c++
os: linux
dist: xenial
cache:
  directories:
    - ext/llvm-7.0.0.src/include
    - ext/llvm-7.0.0.src/sta/bin
    - ext/llvm-7.0.0.src/sta/lib
    - ext/llvm-7.0.0.src/sta/include

compiler: clang

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - ninja-build
    - cmake
    - jq

before_script:
  - git submodule update --init

script:
  - make STATIC_LLVM=1 test
